### ISSUE TITLE
1809 LTSC + debloat Unknown error

### ISSUE THREAD

**Issue by XPower7125** [neelkalpa/InnovPerch#1]
Hello, I've just installed InnovPerch and I got this
![image](https://github.com/neelkalpa/InnovPerch/assets/64551044/3815c367-2577-4143-a363-510bebe14a44)
![image](https://github.com/neelkalpa/InnovPerch/assets/64551044/cf8876d6-9177-4a36-b8ee-0e9b53ed20fd)
Yes I am using ImdusReborn10 (custom build by me)

**Comment by neelkalpa** [comment]
Try original Windows 11/10 because customOS might interfere with the connection to the server
